### ISSUE TITLE
You may want to delete your Twitter auth key on Github

### ISSUE THREAD

**Issue by mason1900** [AmesHarrison/PyFi#1]
You may have accidentally pushed your Twitter API key to the Github. See the following files:
https://github.com/AmesHarrison/PyFi/blob/master/week09/notebooks/fake_auth
https://github.com/AmesHarrison/PyFi/blob/master/week09/notebooks/auth_dict

**Comment by AmesHarrison** [comment]
Wow, thanks!

**Comment by mason1900** [comment]
No, it is still available in repo's history. See the following links:
https://github.com/AmesHarrison/PyFi/blob/a46c135bf74fea9d643820ab743bf5e69af00d00/week09/notebooks/fake_auth
https://github.com/AmesHarrison/PyFi/blob/a46c135bf74fea9d643820ab743bf5e69af00d00/week09/notebooks/auth_dict
Perhaps you may want to try something like:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by AmesHarrison** [comment]
Yes, thank you, this occurred to me later - I actually just went ahead and deleted that Twitter app.
